### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by StevenJohnsonPersonal** [sqlballs/mSQLg2c#236]
https://github.com/sqlballs/mSQLg2c/blob/main/modules/04-ImprovementsInSQLOnTheMicrosoftAzurePlatform.md

Just before the Azure Command-Line section on this page there is a small typo.

It currently reads:
You ca learn more about Jupyter Notebooks here.
      ^^

**Comment by JoshLuedeman** [comment]
@StevenJohnsonPersonal thank you for sending in that issue so quickly. The typo has been fixed. We appreciate your help
